### ISSUE TITLE
Proof is not zero-knowledge

### ISSUE THREAD

**Issue by daira** [ing-bank/zkrangeproof#1]
It leaks the magnitude of the secret value. (Observation by Madars Virza.)

**Comment by peter-rutgers** [comment]
Hi daira,

In HPAKEEqualityConstraint we define the maximum integer to be hidden (security parameter 'b' in the paper by Fabrice Boudot). Because the proofs are intended for an Ethereum context, it is set by default to the maximum of the uint256 data type.

Could you check if you experience the same issue when committing values below 2^256 - 1?

**Comment by madars** [comment]
(Will contact ING privately.)

**Comment by VoR0220** [comment]
Following

**Comment by daira** [comment]
@VoR0220 https://github.com/ing-bank/zkrangeproof#important-note

**Comment by peter-rutgers** [comment]
New version has been released
